### ISSUE TITLE
Heroku deploy

### ISSUE THREAD

**Issue by mahdilupo** [Tomato6966/Musicium#112]
im trying to deploy on heroku and im getting errors

2021-12-11T14:04:18.000352+00:00 heroku[worker.1]: Starting process with command `npx node index.js`
2021-12-11T14:04:18.722252+00:00 heroku[worker.1]: State changed from starting to up
2021-12-11T14:04:19.033980+00:00 heroku[worker.1]: Process exited with status 1
2021-12-11T14:04:18.904222+00:00 app[worker.1]: /app/node_modules/discord.js/src/rest/APIRequest.js:33
2021-12-11T14:04:18.904300+00:00 app[worker.1]:     agent ??= new https.Agent({ ...this.client.options.http.agent, keepAlive: true });
2021-12-11T14:04:18.904303+00:00 app[worker.1]:           ^^^
2021-12-11T14:04:18.904303+00:00 app[worker.1]: 
2021-12-11T14:04:18.904307+00:00 app[worker.1]: SyntaxError: Unexpected token '??='
2021-12-11T14:04:18.904308+00:00 app[worker.1]:     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2021-12-11T14:04:18.904308+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2021-12-11T14:04:18.904311+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-12-11T14:04:18.904311+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-12-11T14:04:18.904311+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2021-12-11T14:04:18.904312+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2021-12-11T14:04:18.904312+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:93:18)
2021-12-11T14:04:18.904312+00:00 app[worker.1]:     at Object.<anonymous> (/app/node_modules/discord.js/src/rest/RESTManager.js:4:20)
2021-12-11T14:04:18.904312+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-12-11T14:04:18.904312+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

can you do like 1 click deploy.

**Comment by Tomato6966** [comment]
use nodejs v16.13

**Comment by mahdilupo** [comment]
heroku and updating node??!!!
problem remains idk why did you closed this

**Comment by sharansukesh1003** [comment]
"engines": { "node": "16.13.1" }
 Add this in your package.json
