### ISSUE TITLE
Pause button is not working 

### ISSUE THREAD

**Issue by iamrahul24** [Tomato6966/Musicium#117]
node v12.16.1
 [antiCrash] :: Unhandled Rejection/Catch
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/runner/music/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/music/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ButtonInteraction.reply (/home/runner/music/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5) {
  method: 'post',
  path: '/interactions/928968747585257523/aW50ZXJhY3Rpb246OTI4OTY4NzQ3NTg1MjU3NTIzOkVySzQwenVueFlFYzJickF3QjZUQ0hFSmxkNm1RdWpvcmhxc1VLMkJ3Mk5aWm9KOHE0d3pKTHluYlRRUHJnU0pXaXQ3ZnpTNzRuVldicjFDWUYza2k1bU5uVW9iS1dhak1ndFRBaGtGVXZqQ3g5WGVyZFBXZjZLZXpWaU9JbzRa/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
} Promise {
  <rejected> DiscordAPIError: Unknown interaction
      at RequestHandler.execute (/home/runner/music/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (/home/runner/music/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
      at async ButtonInteraction.reply (/home/runner/music/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5) {
    method: 'post',
    path: '/interactions/928968747585257523/aW50ZXJhY3Rpb246OTI4OTY4NzQ3NTg1MjU3NTIzOkVySzQwenVueFlFYzJickF3QjZUQ0hFSmxkNm1RdWpvcmhxc1VLMkJ3Mk5aWm9KOHE0d3pKTHluYlRRUHJnU0pXaXQ3ZnpTNzRuVldicjFDWUYza2k1bU5uVW9iS1dhak1ndFRBaGtGVXZqQ3g5WGVyZFBXZjZLZXpWaU9JbzRa/callback',
    code: 10062,
    httpStatus: 404,
    requestData: { json: [Object], files: [] }
  }
  
  
  
  

this is what I am getting every time I press the pause button.

**Comment by iamrahul24** [comment]
Other buttons like autoplay, repeat songs and repeat queue are also not workking.

**Comment by darken248** [comment]
I think you need to update node.js to atleast version 16

**Comment by iamrahul24** [comment]
> I think you need to update node.js to atleast version 16

Ok I will try again updating node.js .

**Comment by Tomato6966** [comment]
u need nodejs at least version 16.6 or higher for it to work + a fast internet conenction
