### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by MondoPIX** [Tomato6966/Musicium#123]
1. Anticrash is spam in the logs

```
0|Musicium_BOT  |  [antiCrash] :: Unhandled Rejection/Catch
0|Musicium_BOT  | TypeError: Cannot read properties of null (reading 'id')
0|Musicium_BOT  |     at Timeout._onTimeout (/home/botdiscord/Musicium/handlers/distubeEvent.js:1040:86)
0|Musicium_BOT  |     at listOnTimeout (node:internal/timers:557:17)
0|Musicium_BOT  |     at processTimers (node:internal/timers:500:7) Promise {
0|Musicium_BOT  |   <rejected> TypeError: Cannot read properties of null (reading 'id')
0|Musicium_BOT  |       at Timeout._onTimeout (/home/botdiscord/Musicium/handlers/distubeEvent.js:1040:86)
0|Musicium_BOT  |       at listOnTimeout (node:internal/timers:557:17)
0|Musicium_BOT  |       at processTimers (node:internal/timers:500:7)
0|Musicium_BOT  | }
```

2. This error comes when you put a link from ytb, but if you put it a couple of times it doesn't give the error anymore

```
0|Musicium_BOT  | Error: connect ETIMEDOUT 2a00:1450:4002:406::200e:443
0|Musicium_BOT  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
0|Musicium_BOT  |   errno: -110,
0|Musicium_BOT  |   code: 'ETIMEDOUT',
0|Musicium_BOT  |   syscall: 'connect',
0|Musicium_BOT  |   address: '2a00:1450:4002:406::200e',
0|Musicium_BOT  |   port: 443,
0|Musicium_BOT  |   name: 'PlayError'
0|Musicium_BOT  | }

```

**Comment by Adstillcodes** [comment]
I am receiving the same errors. Is there any solution to it.  In addition to that I am also receiving this:
![image](https://user-images.githubusercontent.com/70889070/156878181-3618a3f4-8708-48d9-8e41-d920c4138b91.png)
I have no idea why this is happening.
