### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by BiskottoScriptato** [Tomato6966/Musicium#14]
When i run the bot there is this error: TypeError: Cannot read property 'toLowerCase' of undefined
    at new SCDL (C:\Users\Gabry\Desktop\Musicium-5.0-filters-master\node_modules\←[4msoundcloud-downloader←[24m\dist\index.js:92:56)
    at Object.<anonymous> (C:\Users\Gabry\Desktop\Musicium-5.0-filters-master\node_modules\←[4msoundcloud-downloader←[24m\dist\index.js:369:12)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\Gabry\Desktop\Musicium-5.0-filters-master\node_modules\←[4msoundcloud-downloader←[24m\index.js:1:14)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m

**Comment by Tomato6966** [comment]
issue with module not with bot

**Comment by BiskottoScriptato** [comment]
and how do i fix
