### ISSUE TITLE
error at starting

### ISSUE THREAD

**Issue by BestGamersH** [Tomato6966/Musicium#146]
[antiCrash] :: Uncaught Exception/Catch (MONITOR)
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\passport-oauth2\lib\strategy.js:87:34)
    at new Strategy (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\passport-discord\lib\strategy.js:49:20)
    at module.exports (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\dashboard\index.js:35:18)
    at Client.<anonymous> (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\index.js:138:34)
    at Client.emit (node:events:539:35)
    at WebSocketManager.triggerClientReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:379:17)
    at WebSocketManager.checkShardsReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:362:10)
    at WebSocketShard.<anonymous> (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:527:28)
    at WebSocketShard.checkReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketShard.js:513:12) uncaughtException
 [antiCrash] :: Uncaught Exception/Catch
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\passport-oauth2\lib\strategy.js:87:34)
    at new Strategy (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\passport-discord\lib\strategy.js:49:20)
    at module.exports (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\dashboard\index.js:35:18)
    at Client.<anonymous> (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\index.js:138:34)
    at Client.emit (node:events:539:35)
    at WebSocketManager.triggerClientReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:379:17)
    at WebSocketManager.checkShardsReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:362:10)
    at WebSocketShard.<anonymous> (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:527:28)
    at WebSocketShard.checkReady (C:\Users\bestg.HK-LAPTOP\Downloads\Musicium-8.1.1\node_modules\discord.js\src\client\websocket\WebSocketShard.js:513:12) uncaughtException

**Comment by anishdevtech** [comment]
Pass a client id
