### ISSUE TITLE
can't play spotify songs

### ISSUE THREAD

**Issue by cwrsedd** [Tomato6966/Musicium#152]
Error: Couldn't find any data in embed page that we know how to parse
    at /home/runner/Musicium/node_modules/spotify-url-info/src/index.js:65:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SpotifyPlugin.play (/home/runner/Musicium/node_modules/@distube/spotify/dist/index.js:105:22)
    at async Object.run (/home/runner/Musicium/commands/Music/play.js:90:5)

**Comment by King-Ulee** [comment]
Upgrade to the latest version if it's still an error you can use my version 

[link](https://github.com/Julius-Ulee/AmeliaBot-Discord)
replit version [link](https://replit.com/@UzumekiUlee/AmeliaBot-Discord)
