### ISSUE TITLE
 <rejected> ReferenceError: getTracks is not defined | Spotify Album, Tracks problem

### ISSUE THREAD

**Issue by SametKecici** [Tomato6966/Musicium#17]
Spotify Album, Tracks problem

=== UNHANDLED REJECTION ===
Promise:  Promise {
  <rejected> ReferenceError: getTracks is not defined
at Object.run (/app/commands/MUSIC COMMANDS/play.js:79:19)
at Client.<anonymous> (/app/index.js:163:21)
      at Client.emit (events.js:327:22)
      at MessageCreateAction.handle (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
      at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
      at WebSocketShard.onPacket (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
      at WebSocketShard.onMessage (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
      at WebSocket.onMessage (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
      at WebSocket.emit (events.js:315:20)
} Reason:  ReferenceError: getTracks is not defined
at Object.run (/app/commands/MUSIC COMMANDS/play.js:79:19)
at Client.<anonymous> (/app/index.js:163:21)
    at Client.emit (events.js:327:22)
    at MessageCreateAction.handle (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/83956b93-5712-4e49-85b1-487f9ef6b96a/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
=== UNHANDLED REJECTION ===

**Comment by Tomato6966** [comment]
I havent fixed spotify yet, thats because of the pkg i use u can read the docs by yourself if needed
