### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by sam920829** [Tomato6966/Musicium#2]
(node:93632) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Emoji
    at RequestHandler.execute (C:\Users\user\Downloads\Musicium-main\Musicium-main\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (C:\Users\user\Downloads\Musicium-main\Musicium-main\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:93632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:93632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by L0SER8228** [comment]
Use the other version where you don't need to change emojis

**Comment by sam920829** [comment]
TypeError: Cannot read property 'title' of null
    at Object.execute (C:\Users\user\Downloads\Music-Bot-with-Filter-main\Music-Bot-with-Filter-main\Music\play.js:124:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by Tomato6966** [comment]
have you read the readme? the bot uses **CUSTOM emojis** so here is a github which doesnt need those!

https://github.com/Tomato6966/Music-Bot-with-Filter

The bot works, maybe you have not installed the right ffpmeg version or the packages right,  sometimes it doesnt find the song,

make sure to use english letters
