### ISSUE TITLE
When I try to play any song

### ISSUE THREAD

**Issue by ZextroZX** [Tomato6966/Musicium#38]
MinigetError: play(yalgaar) encountered:
Status code: 410
    at ClientRequest.<anonymous> (/home/runner/Musicium-or-Best-Music-Bot-on-Replit/node_modules/miniget/dist/index.js:211:27)
    at Object.onceWrapper (events.js:483:26)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10) {
  statusCode: 410
}

**Comment by Tomato6966** [comment]
Fix your internet connection 
+ use a right cookie

**Comment by ZextroZX** [comment]
I'm using repl.it for hosting and im using right cookie but it's not working. When i updated the ytdl-core it worked but so many filters doesn't even work.
