### ISSUE TITLE
TypeError: client.settings.get(...).map is not a function

### ISSUE THREAD

**Issue by x7s** [Tomato6966/Musicium#50]
https://github.com/Tomato6966/Musicium/blob/87cecd18c478a60f70c7c52a98f77fee8d896a37/handlers/distubeEvent.js#L528

```
TypeError: client.settings.get(...).map is not a function
    at receiveQueueData (home\runner\Musicium-main\handlers\distubeEvent.js:528:59)
    at DisTube.<anonymous> (home\runner\Musicium-main\handlers\distubeEvent.js:36:22)
    at DisTube.emit (node:events:394:28)
    at QueueManager.emit (home\runner\Musicium-main\node_modules\distube\dist\core\DisTubeBase.js:23:29)
    at QueueManager._handleSongFinish (home\runner\Musicium-main\node_modules\distube\dist\core\manager\QueueManager.js:115:22)    
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 [antiCrash] :: Uncaught Exception/Catch (MONITOR)
```

**Comment by Tomato6966** [comment]
Do this:
 client.settings.get(newQueue.id, `djroles`).array().map(r => `<@&${r}>`);
