### ISSUE TITLE
TypeError: client.settings.get(...).map is not a function

### ISSUE THREAD

**Issue by x7s** [Tomato6966/Musicium#51]
https://github.com/Tomato6966/Musicium/blob/87cecd18c478a60f70c7c52a98f77fee8d896a37/commands/Queue/status.js#L68

```
TypeError: client.settings.get(...).map is not a function
    at Object.run (home\runner\Musicium-main\commands\Queue\status.js:68:59)
    at module.exports (home\runner\Musicium-main\events\guild\messageCreate.js:135:19)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (home\runner\Musicium-main\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14)    
    at Object.module.exports [as MESSAGE_CREATE] (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)   
    at WebSocketShard.onMessage (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)  
    at WebSocket.onMessage (home\runner\Musicium-main\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
```

**Comment by Tomato6966** [comment]
do: client.settings.get(newQueue.id, `djroles`).array().map(r => `<@&${r}>`);

**Comment by x7s** [comment]
now another error i try to search at VS Code client.settings.get(newQueue.id, and where i see djroles to put double quotes but that not work and give me the error like array is not function or somethink else 
```
 [antiCrash] :: Multiple Resolves
ReferenceError: djroles is not defined
    at receiveQueueData (home\runner\Musicium-main\handlers\distubeEvent.js:528:48)
    at DisTube.<anonymous> (home\runner\Musicium-main\handlers\distubeEvent.js:36:22)
    at DisTube.emit (node:events:394:28)
    at DisTube.playVoiceChannel (home\runner\Musicium-main\node_modules\distube\dist\DisTube.js:203:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (home\runner\Musicium-main\commands\Music\play.js:90:5)
TypeError: client.settings.get(...).map is not a function
    at Object.run (home\runner\Musicium-main\commands\Queue\status.js:68:59)
    at module.exports (home\runner\Musicium-main\events\guild\messageCreate.js:135:19)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (home\runner\Musicium-main\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14)    
    at Object.module.exports [as MESSAGE_CREATE] (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)   
    at WebSocketShard.onMessage (home\runner\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)  
    at WebSocket.onMessage (home\runner\Musicium-main\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
 [antiCrash] :: Multiple Resolves
```

**Comment by Tomato6966** [comment]
check the latest src?
