### ISSUE TITLE
and fix Dj-Roles in dashboard not only dj roles command

### ISSUE THREAD

**Issue by aziz191546** [Tomato6966/Musicium#55]
TypeError: client.settings.get(...).map is not a function
    at receiveQueueData (/home/runner/***/handlers/distubeEvent.js:528:59)
    at DisTube.<anonymous> (/home/runner/***/handlers/distubeEvent.js:36:22)
    at DisTube.emit (node:events:394:28)
    at DisTube.playVoiceChannel (/home/runner/***/node_modules/distube/dist/DisTube.js:203:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.run (/home/runner/***/commands/Music/play.js:90:5)

**Comment by aziz191546** [comment]
i cant delete Dj-Roles if set dj role from dashboard and i get some errors

**Comment by Tomato6966** [comment]
u use the latest version of the github?

**Comment by aziz191546** [comment]
yeah

**Comment by aziz191546** [comment]
problem on dashboard

**Comment by Tomato6966** [comment]
hmmm for me its alright whats your host

**Comment by aziz191546** [comment]
replit

**Comment by Tomato6966** [comment]
imma take a look into that but for me its alright sorry
