### ISSUE TITLE
error after discord authorisation

### ISSUE THREAD

**Issue by xcuzimfna** [Tomato6966/Musicium#59]
after i authorise discord i get this error:
TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/fate/node_modules/passport-oauth2/lib/strategy.js:372:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/fate/node_modules/passport-oauth2/lib/strategy.js:419:16)
    at /home/runner/fate/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/runner/fate/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/fate/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/fate/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Tomato6966** [comment]
Add oauth2 redirect in your Bot
From: https://i.imgur.com/EYQLCNT.png
TO: https://i.imgur.com/gBTUyDw.png
