### ISSUE TITLE
OAuth2Strategy

### ISSUE THREAD

**Issue by knightwanter** [Tomato6966/Musicium#60]
i am getting error : 
 
 [antiCrash] :: Uncaught Exception/Catch (MONITOR)
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/runner/Musicium-1/node_modules/passport-oauth2/lib/strategy.js:87:34)
    at new Strategy (/home/runner/Musicium-1/node_modules/passport-discord/lib/strategy.js:49:20)
    at module.exports (/home/runner/Musicium-1/dashboard/index.js:35:18)

**Comment by Tomato6966** [comment]
https://github.com/Tomato6966/Musicium/issues/59
