### ISSUE TITLE
Windows Version Problem

### ISSUE THREAD

**Issue by Gj4meZ** [Tomato6966/Musicium#62]
When i Want to Rn The Project on my VPS 
after i used 
npm i 
i use
node index
and Shows me This Error
------------
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\azureuser\Desktop\ionia\node_modules\@distube\spotify\dist\index.js:44:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\azureuser\Desktop\ionia\index.js:37:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
-------------
and i Cant install distube 3.0.0beta.27 or 28
I Tryed To Download But Gives me This Error :
--------
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
---------
Why This Happens?

**Comment by Tomato6966** [comment]
install git?
It tells you even in the error...

https://git-scm.com/downloads
