### ISSUE TITLE
Can't disable anti crash

### ISSUE THREAD

**Issue by BiskottoScriptato** [Tomato6966/Musicium#63]
If i disable the anti crash it gaves me an error when i start the bot: 

C:\Users\Gabry\Desktop\Musicium-main\node_modules\passport-oauth2\lib\strategy.js:87
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\Gabry\Desktop\Musicium-main\node_modules\passport-oauth2\lib\strategy.js:87:34)
    at new Strategy (C:\Users\Gabry\Desktop\Musicium-main\node_modules\passport-discord\lib\strategy.js:49:20)
    at module.exports (C:\Users\Gabry\Desktop\Musicium-main\dashboard\index.js:35:18)
    at Client.<anonymous> (C:\Users\Gabry\Desktop\Musicium-main\index.js:136:34)
    at Client.emit (node:events:406:35)
    at WebSocketManager.triggerClientReady (C:\Users\Gabry\Desktop\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:378:17)
    at WebSocketManager.checkShardsReady (C:\Users\Gabry\Desktop\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:361:10)
    at WebSocketShard.<anonymous> (C:\Users\Gabry\Desktop\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:183:14)
    at WebSocketShard.emit (node:events:394:28)
    at WebSocketShard.checkReady (C:\Users\Gabry\Desktop\Musicium-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:474:12)

**Comment by TOXIC6163** [comment]
IT PREVENTS FROM CODE TO CRASH SO IF IT IS DISABLED IT MIGHT GET YOUR BOT ERROR / CRASH. SO ALWAYS MAKE ANTI-CRASH _ENABLED_  **TO MAKE YOUR BOT RUN NON-STOP**

**Comment by BiskottoScriptato** [comment]
I know but when i play a live stream or a long video it stops after 3 seconds

**Comment by TOXIC6163** [comment]
> I know but when i play a live stream or a long video it stops after 3 seconds

if see the bug again please go [here](https://www.discord.com/channels/773668217163218944/853379230683365416) with the screenshot of it. supporters will help u _ASAP_

**Comment by BlueCrafter6** [comment]
peepa

**Comment by Tomato6966** [comment]
add your client secret to settings.json
read readme.md
