### ISSUE TITLE
Error while login in dashboard

### ISSUE THREAD

**Issue by ojomangame** [Tomato6966/Musicium#76]
when i login in dashboard, it gives error on site:

TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/Musicium/node_modules/passport-oauth2/lib/strategy.js:372:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/Musicium/node_modules/passport-oauth2/lib/strategy.js:419:16)
    at /home/runner/Musicium/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/runner/Musicium/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/Musicium/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/Musicium/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

what i need to do?
![image](https://user-images.githubusercontent.com/83218418/135495656-a41f521a-9577-4f60-a410-168d13f83d81.png)

**Comment by ojomangame** [comment]
I solved this problem, problem - on repl.it you have an old version of dashboard( but i download a new version from this github and upload new dashboard folder to my repl

**Comment by Tomato6966** [comment]
add a secret...

**Comment by Tomato6966** [comment]
but good you solved it yourself

**Comment by ojomangame** [comment]
secret was pasted...
