### ISSUE TITLE
[antiCrash] :: Uncaught Exception/Catch

### ISSUE THREAD

**Issue by iM0hamed** [Tomato6966/Musicium#83]
[antiCrash] :: Uncaught Exception/Catch
TypeError: Cannot read properties of null (reading 'toString')
    at Map.[fetchCheck] (/home/ubuntu/Musicium/node_modules/enmap/src/index.js:1137:15)
    at Map.ensure (/home/ubuntu/Musicium/node_modules/enmap/src/index.js:616:22)
    at module.exports (/home/ubuntu/Musicium/events/guild/interactionCreate.js:9:19)
    at Client.emit (node:events:390:28)
    at InteractionCreateAction.handle (/home/ubuntu/Musicium/node_modules/discord.js/src/client/actions/InteractionCreate.js:66:12)
    at Object.module.exports [as INTERACTION_CREATE] (/home/ubuntu/Musicium/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/ubuntu/Musicium/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (/home/ubuntu/Musicium/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/home/ubuntu/Musicium/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/home/ubuntu/Musicium/node_modules/discord.js/node_modules/ws/lib/event-target.js:199:18) uncaughtException

**Comment by Tomato6966** [comment]
Only happens on dm interactions.. 
You need to check if the interaction is in a guild first
