### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by MashedTuna** [Tomato6966/Musicium#87]
TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/runner/LofiStation/node_modules/passport-oauth2/lib/strategy.js:372:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/runner/LofiStation/node_modules/passport-oauth2/lib/strategy.js:419:16)
    at /home/runner/LofiStation/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /home/runner/LofiStation/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/runner/LofiStation/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/runner/LofiStation/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by MashedTuna** [comment]
i fixed myself
